name: Build and Push to ECR

on:
  push:
    branches:
      - deployment

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push
        run: |
          docker build -t crag-rag-app .
          docker tag crag-rag-app:latest 380610849617.dkr.ecr.us-east-1.amazonaws.com/crag-rag-app:latest
          docker push 380610849617.dkr.ecr.us-east-1.amazonaws.com/crag-rag-app:latest